/**
 * This class file was automatically generated by jASN1 v1.11.3 (http://www.beanit.com)
 */

package b2.ccsds.csts.buffered.data.processing.pdus;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;
import com.beanit.jasn1.ber.types.string.*;

import b2.ccsds.csts.common.operations.pdus.ProcessDataInvocation;
import b2.ccsds.csts.data.processing.pdus.DataProcessingPdu;

public class BufferedDataProcessingPdu extends DataProcessingPdu {

	private static final long serialVersionUID = 1L;

	public BufferedDataProcessingPdu() {
	}

	public BufferedDataProcessingPdu(byte[] code) {
		super(code);
	}

}
