/**
 * This class file was automatically generated by jASN1 v1.11.3-SNAPSHOT (http://www.beanit.com)
 */

package frm.csts.functional.resource.types;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;
import com.beanit.jasn1.ber.types.string.*;


public class AntPrecipitationRate extends BerInteger {

	private static final long serialVersionUID = 1L;

	public AntPrecipitationRate() {
	}

	public AntPrecipitationRate(byte[] code) {
		super(code);
	}

	public AntPrecipitationRate(BigInteger value) {
		super(value);
	}

	public AntPrecipitationRate(long value) {
		super(value);
	}

}
