package esa.egos.csts.api.enumerations;

public enum CstsResult {
	UNEXPECTED_OPERATION_TYPE,
	UNSUPPORTED_PROCEDURE_ROLE,
	OPERATION_TYPE_NOT_SUPPORTED,
	NOT_APPLICABLE,
	IGNORED,
	SUCCESS,
	ALREADY_BOUND,
	ALREADY_UNBOUND,
	FAILURE,
	ABORTED,
	PROTOCOL_ERROR,
	COMMUNICATIONS_FAILURE,
	INVOCATION_ARGUMENT_VERIFICATION_FAILED
}
