package esa.egos.csts.api.enumerations;

public enum ParameterType {
	INTEGER,
	UNSIGNED_INTEGER,
	POSITIVE_INTEGER,
	DURATION,
	CHARACTER_STRING,
	BOOLEAN,
	OCTET_STRING,
	REAL,
	TIME,
	ENUMERATED,
	PUBLISHED_IDENTIFIER,
	OBJECT_IDENTIFIER,
	EXTENDED;
}
