/**
 * This class file was automatically generated by jASN1 v1.11.3-SNAPSHOT (http://www.beanit.com)
 */

package b2.ccsds.on.change.option.cyclic.report.pdus;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.jasn1.ber.*;
import com.beanit.jasn1.ber.types.*;
import com.beanit.jasn1.ber.types.string.*;

import b2.ccsds.csts.common.types.Extended;
import b2.ccsds.csts.unbuffered.data.delivery.pdus.UnbufferedDataDeliveryPdu;

public class OnChangeOptCyclicReportStartInvocExt implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);

	public byte[] code = null;
	private BerBoolean onChangeOnly = null;
	private Extended onChangeOptCyclicReportStartInvocExtExtension = null;
	
	public OnChangeOptCyclicReportStartInvocExt() {
	}

	public OnChangeOptCyclicReportStartInvocExt(byte[] code) {
		this.code = code;
	}

	public void setOnChangeOnly(BerBoolean onChangeOnly) {
		this.onChangeOnly = onChangeOnly;
	}

	public BerBoolean getOnChangeOnly() {
		return onChangeOnly;
	}

	public void setOnChangeOptCyclicReportStartInvocExtExtension(Extended onChangeOptCyclicReportStartInvocExtExtension) {
		this.onChangeOptCyclicReportStartInvocExtExtension = onChangeOptCyclicReportStartInvocExtExtension;
	}

	public Extended getOnChangeOptCyclicReportStartInvocExtExtension() {
		return onChangeOptCyclicReportStartInvocExtExtension;
	}

	public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		codeLength += onChangeOptCyclicReportStartInvocExtExtension.encode(reverseOS);
		
		codeLength += onChangeOnly.encode(reverseOS, true);
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		subCodeLength += berTag.decode(is);
		if (berTag.equals(BerBoolean.tag)) {
			onChangeOnly = new BerBoolean();
			subCodeLength += onChangeOnly.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		onChangeOptCyclicReportStartInvocExtExtension = new Extended();
		subCodeLength += onChangeOptCyclicReportStartInvocExtExtension.decode(is, berTag);
		if (subCodeLength == totalLength) {
			return codeLength;
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		sb.append("\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (onChangeOnly != null) {
			sb.append("onChangeOnly: ").append(onChangeOnly);
		}
		else {
			sb.append("onChangeOnly: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (onChangeOptCyclicReportStartInvocExtExtension != null) {
			sb.append("onChangeOptCyclicReportStartInvocExtExtension: ");
			onChangeOptCyclicReportStartInvocExtExtension.appendAsString(sb, indentLevel + 1);
		}
		else {
			sb.append("onChangeOptCyclicReportStartInvocExtExtension: <empty-required-field>");
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

