/**
 * This class file was automatically generated by jASN1 v1.8.1 (http://www.openmuc.org)
 */

package ccsds.csts.fw.procedure.parameters.events.directives;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;

import ccsds.csts.common.types.AuthorityIdentifier;
import ccsds.csts.common.types.BufferSize;
import ccsds.csts.common.types.DataTransferMode;
import ccsds.csts.common.types.DeliveryLatencyLimit;
import ccsds.csts.common.types.DeliveryMode;
import ccsds.csts.common.types.IntPos;
import ccsds.csts.common.types.Label;
import ccsds.csts.common.types.ProcessingLatencyLimit;
import ccsds.csts.common.types.ServiceUserRespTimer;
import ccsds.csts.service.instance.id.ServiceInstanceIdentifier;

public class PBDDreturnBufferSizeType extends BufferSize {

	private static final long serialVersionUID = 1L;

	public PBDDreturnBufferSizeType() {
	}

	public PBDDreturnBufferSizeType(byte[] code) {
		super(code);
	}

	public PBDDreturnBufferSizeType(BigInteger value) {
		super(value);
	}

	public PBDDreturnBufferSizeType(long value) {
		super(value);
	}

}
