/**
 * This class file was automatically generated by jASN1 v1.8.1 (http://www.openmuc.org)
 */

package ccsds.csts.common.types;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class Time implements Serializable {

	private static final long serialVersionUID = 1L;

	public byte[] code = null;
	private TimeCCSDSMilli ccsdsFormatMilliseconds = null;
	private TimeCCSDSPico ccsdsFormatPicoseconds = null;
	
	public Time() {
	}

	public Time(byte[] code) {
		this.code = code;
	}

	public void setCcsdsFormatMilliseconds(TimeCCSDSMilli ccsdsFormatMilliseconds) {
		this.ccsdsFormatMilliseconds = ccsdsFormatMilliseconds;
	}

	public TimeCCSDSMilli getCcsdsFormatMilliseconds() {
		return ccsdsFormatMilliseconds;
	}

	public void setCcsdsFormatPicoseconds(TimeCCSDSPico ccsdsFormatPicoseconds) {
		this.ccsdsFormatPicoseconds = ccsdsFormatPicoseconds;
	}

	public TimeCCSDSPico getCcsdsFormatPicoseconds() {
		return ccsdsFormatPicoseconds;
	}

	public int encode(BerByteArrayOutputStream os) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				os.write(code[i]);
			}
			return code.length;
		}

		int codeLength = 0;
		if (ccsdsFormatPicoseconds != null) {
			codeLength += ccsdsFormatPicoseconds.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 1
			os.write(0x81);
			codeLength += 1;
			return codeLength;
		}
		
		if (ccsdsFormatMilliseconds != null) {
			codeLength += ccsdsFormatMilliseconds.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 0
			os.write(0x80);
			codeLength += 1;
			return codeLength;
		}
		
		throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
	}

	public int decode(InputStream is) throws IOException {
		return decode(is, null);
	}

	public int decode(InputStream is, BerTag berTag) throws IOException {

		int codeLength = 0;
		BerTag passedTag = berTag;

		if (berTag == null) {
			berTag = new BerTag();
			codeLength += berTag.decode(is);
		}

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 0)) {
			ccsdsFormatMilliseconds = new TimeCCSDSMilli();
			codeLength += ccsdsFormatMilliseconds.decode(is, false);
			return codeLength;
		}

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 1)) {
			ccsdsFormatPicoseconds = new TimeCCSDSPico();
			codeLength += ccsdsFormatPicoseconds.decode(is, false);
			return codeLength;
		}

		if (passedTag != null) {
			return 0;
		}

		throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		BerByteArrayOutputStream os = new BerByteArrayOutputStream(encodingSizeGuess);
		encode(os);
		code = os.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		if (ccsdsFormatMilliseconds != null) {
			sb.append("ccsdsFormatMilliseconds: ").append(ccsdsFormatMilliseconds);
			return;
		}

		if (ccsdsFormatPicoseconds != null) {
			sb.append("ccsdsFormatPicoseconds: ").append(ccsdsFormatPicoseconds);
			return;
		}

		sb.append("<none>");
	}

}

