package esa.egos.csts.api.directives;

public enum DirectiveQualifierType {
	LOCAL_PROCEDURE_DIRECTIVE_QUALIFIER,
	SERVICE_PROCEDURE_DIRECTIVE_QUALIFIER,
	FUNCTIONAL_RESOURCE_DIRECTIVE_QUALIFIER,
	EXTENDED;
}
