package esa.egos.csts.api.enums;

public enum ListOfParamatersEnum {
	EMPTY,
	LIST_NAME,
	FUNCTIONAL_RESOURCE_TYPE,
	FUNCTIONAL_RESOURCE_NAME,
	PROCEDURE_TYPE,
	PROCEDURE_INSTANCE_IDENTIFIER,
	LABELS_SET,
	NAMES_SET;
}
