package esa.egos.csts.api.enums;

public enum ListOfParametersDiagnosticsEnum {
	UNDEFINED_DEFAULT,
	UNKNOWN_LIST_NAME,
	UNKNOWN_FUNCTIONAL_RESOURCE_TYPE,
	UNKNOWN_FUNCTIONAL_RESOURCE_NAME,
	UNKNOWN_PROCEDURE_TYPE,
	UNKNOWN_PROCEDURE_INSTANCE_IDENTIFIER,
	UNKNOWN_PARAMETER_IDENTIFIER;
}
