package esa.egos.csts.api.enums;

public enum OperationType {
	
	OT_BIND_INVOCATION,
	OT_BIND_RETURN,
	OT_UNBIND_INVOCATION,
	OT_UNBIND_RETURN,
	OT_PEER_ABORT_INVOCATION,
	OT_EXECUTE_DIRECTIVE_INVOCATION,
	OT_EXECUTE_DIRECTIVE_ACKNOWLEDGE,
	OT_EXECUTE_DIRECTIVE_RETURN,
	OT_GET_INVOCATION,
	OT_GET_RETURN,
	OT_GET_POS_RETURN_EXT,
	OT_GET_DIAGNOSTIC_EXT,
	OT_NOTIFY_INVOCATION,
	OT_PROCESS_DATA_INVOCATION,
	OT_PROCESS_DATA_RETURN,
	OT_START_INVOCATION,
	OT_START_RETURN,
	OT_START_DIAGNOSTIC_EXT,
	OT_STOP_INVOCATION,
	OT_STOP_RETURN,
	OT_TRANSFER_DATA_INVOCATION;
	
}
